version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.4.0
    steps:
      - checkout
      - run: npm i --verbose
      - run: sudo npm i -g codecov
      - run: npm test -- --coverage
      - store_artifacts:
          path: coverage
          prefix: coverage
  build:
    docker:
      - image: circleci/node:10.4.0
    steps:
      - checkout
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
